spring:
  datasource:
    url: jdbc:mysql://192.168.3.23:3306/jpa?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#      控制台显示sql
    show-sql: true
#  http:
#    encoding:
#      charset: UTF-8
#      force: true
#      enabled: true
